apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  containers:
  - name: vproapp
    image: sharonraju143/finalimage:latest
    imagePullPolicy: Always
    ports:
    - name: vproapp-port
      containerPort: 8080 
